## CTMC M/M/1/K model

In [21]:
# import libraries
import numpy as np
from jmarkov.ctmc import ctmc

### Build the model

In [22]:
# define problem parameters
lda = 1
mu = 2 
K = 3

In [23]:
# build generator matrix Q
Q = np.zeros((K+1,K+1))
for i in range(K+1):
    # arrivals 
    if i < K:
        Q[i,i+1] = lda
        Q[i,i] -= lda
    # services
    if i > 0:
        Q[i,i-1] = mu
        Q[i,i] -= mu

mc = ctmc(Q)
print(f'Q={mc.generator}')

Q=[[-1.  1.  0.  0.]
 [ 2. -3.  1.  0.]
 [ 0.  2. -3.  1.]
 [ 0.  0.  2. -2.]]


In [24]:
# build initial condition probability vector
alpha = np.zeros(K+1)
alpha[0] = 1
print(f'alpha={alpha}')

alpha=[1. 0. 0. 0.]


### Evaluate transient distribution

In [25]:
t= 0.01
pi_t=mc.transient_probabilities(t, alpha)
print(f'pi({t})={pi_t}')

pi(0.01)=[9.90148185e-01 9.80280196e-03 4.88498232e-05 1.62964545e-07]


In [26]:
t= 0.1
pi_t=mc.transient_probabilities(t, alpha)
print(f'pi({t})={pi_t}')

pi(0.1)=[9.13338924e-01 8.25438972e-02 3.98360383e-03 1.33574643e-04]


In [27]:
t= 0.5
pi_t=mc.transient_probabilities(t, alpha)
print(f'pi({t})={pi_t}')

pi(0.5)=[0.72625861 0.22126981 0.0450792  0.00739239]


In [28]:
t= 1
pi_t=mc.transient_probabilities(t, alpha)
print(f'pi({t})={pi_t}')

pi(1)=[0.63393794 0.25769503 0.08370483 0.02466221]


In [29]:
t= 1.5
pi_t=mc.transient_probabilities(t, alpha)
print(f'pi({t})={pi_t}')

pi(1.5)=[0.59099503 0.26475986 0.10455779 0.03968732]


In [30]:
t= 10
pi_t=mc.transient_probabilities(t, alpha)
print(f'pi({t})={pi_t}')

pi(10)=[0.53334468 0.26666667 0.13332766 0.06666099]


### Evaluate stationary distribution

In [31]:
ss = mc.steady_state()
print(f'pi={ss}')

pi=[0.53333333 0.26666667 0.13333333 0.06666667]
